const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(__dirname+'/../dist/app.js','utf8').split('let repo,lessonIndex=')[0];
const context=vm.createContext({console});vm.runInContext(source+';globalThis.api={Repo,lessons,seed};',context);
const {Repo,lessons,seed}=context.api;
let errors=[];lessons.forEach((l,i)=>{const r=seed(l.seed);l.steps.forEach((s,j)=>{try{r.run(s.cmd);}catch(e){if(i===12&&j===0&&e.message.includes('fast-forward'))return;errors.push(`${i+1}.${j+1}: ${s.cmd}: ${e.message}`);}});if(r.pending)errors.push(`${i+1}: pending operation`);});assert.deepEqual(errors,[]);
let r=seed('feature');r.run('git merge feature/booking-api');assert.equal(r.tip(),'D');assert.equal(Object.keys(r.commits).length,4);
r=seed('diverged');r.run('git merge feature/booking-api');assert.equal(r.commits[r.tip()].parents.length,2);
r=seed('diverged');r.run('git switch feature/booking-api');r.run('git rebase origin/develop');assert.equal(r.commits[r.tip()].parents[0],'F');assert.equal(r.commits.F.parents[0],'E');assert(r.commits.C&&r.commits.D);
r=seed('conflict');r.run('git merge feature/booking-api');assert.equal(r.pending.type,'merge');assert.throws(()=>r.run('git commit -m "bad"'));r.run('git merge --abort');assert.equal(r.tip(),'D');assert.equal(r.pending,null);
r=seed('conflict');r.run('git switch feature/booking-api');r.run('git rebase develop');assert.equal(r.pending.type,'rebase');r.run('edit app/api/booking.py "resolved"');r.run('git add .');r.run('git rebase --continue');assert.equal(r.pending,null);assert.equal(r.commits[r.tip()].parents[0],'D');
r=new Repo();r.run('edit app/service.py "staged"');r.run('git add .');r.run('edit app/service.py "unstaged"');r.run('git restore app/service.py');assert.equal(r.work['app/service.py'],'staged');r.run('git commit -m "save"');r.run('git reset --soft HEAD~1');assert.equal(r.index['app/service.py'],'staged');r.run('git reset --mixed HEAD');assert.equal(r.index['app/service.py'],'tax_rate = 0.10');assert.equal(r.work['app/service.py'],'staged');r.run('git reset --hard HEAD');assert.equal(r.work['app/service.py'],'tax_rate = 0.10');
r=new Repo();r.run('lab teammate');assert.equal(r.tracking.develop,'B');assert.equal(r.remote.develop,'C');r.run('git fetch origin');assert.equal(r.tracking.develop,'C');assert.equal(r.branches.develop,'B');
r=new Repo();r.run('git switch --detach B');r.run('edit app/service.py "new"');r.run('git add .');r.run('git commit -m "detached"');assert.equal(r.tip(),'C');assert.equal(r.branches.develop,'B');
r=new Repo();r.run('edit app/service.py "tax_rate = 0.08"');r.run('git add .');assert.equal(r.run('git diff'),'No differences.');r.run('edit app/service.py "tax_rate = 0.05"');
assert(r.run('git diff').includes('- tax_rate = 0.08\n+ tax_rate = 0.05'));
assert(r.run('git diff --staged').includes('- tax_rate = 0.10\n+ tax_rate = 0.08'));
assert(r.run('git diff HEAD').includes('- tax_rate = 0.10\n+ tax_rate = 0.05'));
r.run('edit new.txt "untracked"');assert(!r.run('git diff').includes('new.txt'));
console.log(`PASS: all ${lessons.length-1} guided scenarios, expected ff-only rejection, merge parentage, rebase replay/conflict, abort, index/restore/reset, remote tracking and detached HEAD.`);
